export default [
    {
        id: '1',
        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '8.30',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '2',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '7.10',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '3',
        name: 'Chicken Burger',
        ingredients: 'Fried Chicken',
        price: '5.10',
        image: require('../assets/chickenBurger.png'),
    },
    {
        id: '4',
        name: 'Sushi Makizushi',
        ingredients: 'Salmon Meat',
        price: '9.55',
        image: require('../assets/sushiMakizushi.png'),
    },
    {
        id: '5',
        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '8.30',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '6',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '7.10',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '7',
        name: 'Chicken Burger',
        ingredients: 'Fried Chicken',
        price: '5.10',
        image: require('../assets/chickenBurger.png'),
    },
    {
        id: '8',
        name: 'Sushi Makizushi',
        ingredients: 'Salmon Meat',
        price: '9.55',
        image: require('../assets/sushiMakizushi.png'),
    },
    {
        id: '9',
        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '8.30',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '10',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '7.10',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '11',
        name: 'Chicken Burger',
        ingredients: 'Fried Chicken',
        price: '5.10',
        image: require('../assets/chickenBurger.png'),
    },
    {
        id: '12',
        name: 'Sushi Makizushi',
        ingredients: 'Salmon Meat',
        price: '9.55',
        image: require('../assets/sushiMakizushi.png'),
    },
];